# Generated by Django 2.1.7 on 2019-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_auto_20190318_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
